### ISSUE TITLE
how to train 30B model

### ISSUE THREAD

**Issue by MeJerry215** [zankner/Hydra#2]
Could you give me some examples about training 30b model？
If using examples command line to run 30b model training， will gets OOM exceptions.

Running in NVIDIA A100-SXM4-80GB * 8 enviroments.

@zankner

**Comment by zankner** [comment]
To get 30B model training, we pre-computed the hidden states and stored them to disk and then just loaded the hidden states to train.

To compute the base models' hidden states over the dataset run:

```bash
torchrun --nproc_per_node=8 hydra/data/build_hidden_states.py --model_name_or_path lmsys/vicuna-33b-v1.3 --data_path data/sharegpt/raw/val.json --split "val" --remote_upload_base "data/sharegpt/" --lazy_preprocess True --bf16 True --model_max_length 2048 --tf32 True --logging_steps 5 --per_device_eval_batch_size 16 --output_dir foo

torchrun --nproc_per_node=8 hydra/data/build_hidden_states.py --model_name_or_path lmsys/vicuna-33b-v1.3 --data_path data/sharegpt/raw/train.json --split "train" --remote_upload_base "data/sharegpt/" --lazy_preprocess True --bf16 True --model_max_length 2048 --tf32 True --logging_steps 5 --per_device_eval_batch_size 16 --output_dir foo
```

This will pre-compute the hidden states for the val split and then the train split. (Note: IIRC the final dataset size is close to 1TB so it will take up a lot of space)

After you build the hidden states, you can train on those hidden states by updating the argument `data_path` to be:
```bash
--data_path --data_path data/sharegpt/vicuna-33b-v1.3_off_0/
```
and also passing in the flag
```bash
--precomputed_data True
```

Other than that, the rest of the training command can stay the same.

Hope this helps, if you have any issues with it please let me know.
