### ISSUE TITLE
The difference and connection between _grounded_proposal and _ungrounded_proposal

### ISSUE THREAD

**Issue by reflectionie** [zankner/Hydra#3]
Hi, thank you for your wonderful work! Can I ask about the difference and connection between _grounded_proposal and _ungrounded_proposal?

**Comment by xinlong-yang** [comment]
I have the same question 👍

**Comment by zankner** [comment]
Thanks for the kind words!

The difference is just whether heads have sequential dependence, so grounded == sequential dependence, ungrounded == no sequential dependence. So doing grounded is what Hydra proposes and ungrounded is the original Meudsa work essentially. 

Ungrounded proposals are also only supported for MLP Head and not PrefixMLP. I would recommend doing grounded proposals for the speed boost Hydra gives 😁

**Comment by xinlong-yang** [comment]
> Thanks for the kind words!
> 
> The difference is just whether heads have sequential dependence, so grounded == sequential dependence, ungrounded == no sequential dependence. So doing grounded is what Hydra proposes and ungrounded is the original Meudsa work essentially.
> 
> Ungrounded proposals are also only supported for MLP Head and not PrefixMLP. I would recommend doing grounded proposals for the speed boost Hydra gives 😁

I see, thanks for your response

**Comment by xinlong-yang** [comment]
@zankner  Sorry I have another question. In your repo, hydra choices 'mc_sim_7b_63' is the same to medusa's? or you use another dataset to calculate for a better sparse tree structure? Do you think we should do that or just follow medusa's. Thanks!

**Comment by zankner** [comment]
Yeah thats the same as Medusa's choices. We have done some work to calculate the optimal trees and will update the repo with it once finishes, but in the batch size 1 case it doesn't make much of a difference so I would recommend just sticking with medusa choices for now.
