### ISSUE TITLE
OOM issue

### ISSUE THREAD

**Issue by ShivangiAg** [zankner/Hydra#4]
I am getting OOM in 40 GB available GPU memory(P4 instance) after increasing number of layers and heads to 4. This commands I am using torchrun --nproc_per_node=1 hydra/train/train.py --model_name_or_path lmsys/vicuna-7b-v1.3  --data_path data/sharegpt/raw/  --bf16 True  --output_dir ckpts  --hydra_num_heads 4  --hydra_num_layers 4. I tried with 1 head and 1 layer, it is running fine. Also I tried with precomputed data, still it is showing OOM error. What is required configuration to run this?

**Comment by zankner** [comment]
You can try decreasing the micro_batch_size. Could you also post the command you use for pre-computed data.

**Comment by zankner** [comment]
Closing for now but feel free to open at any time @ShivangiAg
