### ISSUE TITLE
Eagle implementation

### ISSUE THREAD

**Issue by FatPigeorz** [zankner/Hydra#5]
I noticed that your implement Eagle in `eagle_head.py`, is that equivalent to the [Eagle codebase](https://github.com/SafeAILab/EAGLE)? have you test it?

**Comment by zankner** [comment]
We tried to replicate it as closely as possible. The heads achieve the same acceptance length but have a slightly lower throughput from when we tested it. Can't promise the heads work in the current version of the code base since we tested them a while ago, sorry.
