### ISSUE TITLE
About 'Cross-Attention_head'

### ISSUE THREAD

**Issue by xinlong-yang** [zankner/Hydra#6]
Hi, thanks for your great work! I want to ask about the "cross-attention-head.py", what's the use of cross-attention head? I know eagle head, mlp head and prefix head, but I'm not clear about the meaning of cross-attention head, could you please introduce? Thanks!

**Comment by zankner** [comment]
@xinlong-yang It was an earlier architecture we experimented with, where tokens in the speculation would attend both to previous tokens in the speculation as well as the already decoded prefix. We chose to not go with this method as it introduced more overhead and had worse results than the prefix-mlp heads.

**Comment by xinlong-yang** [comment]
@zankner I see, thanks
